import type { Metadata } from 'next'
import { Source_Serif_4 } from 'next/font/google'
import './globals.scss'

import Footer from './components/Footer'

const inter = Source_Serif_4({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			{/* <body className={inter.className}> */}
			<body>
				{children}

				<Footer />
			</body>
		</html>
	)
}
