// import type { Metadata } from 'next'
import { Source_Serif_4 } from 'next/font/google'
import './globals.scss'

import { Suspense } from 'react'

import Header from './components/Header'
import Thumbnails from './components/Thumbnails'

import Footer from './components/Footer'

const SourceSerif = Source_Serif_4({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			{/* <body className={inter.className}> */}
			<body className={SourceSerif.className}>
				<Suspense fallback={<p>Loading ...</p>}>
					<Header />
				</Suspense>
				{children}
				<Suspense fallback={<p>Loading ...</p>}>
					<Footer />
				</Suspense>
			</body>
		</html>
	)
}
